//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcuityScheduling
    {
        public int Id { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> AptDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Clinic { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Location { get; set; }
        public Nullable<int> PatientID { get; set; }
    }
}
