//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int TableID { get; set; }
        public string TableName { get; set; }
        public string TypeObject { get; set; }
        public string UpdateMethod { get; set; }
        public string InsertMethod { get; set; }
        public string SelectMethod { get; set; }
        public string SelectSingle { get; set; }
    }
}
