//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime ApptStart { get; set; }
        public System.DateTime ApptEnd { get; set; }
        public int ProviderID { get; set; }
        public int AppointmentTypeID { get; set; }
        public int StatusID { get; set; }
        public bool AllDay { get; set; }
        public bool EmailOnChange { get; set; }
        public int Results { get; set; }
        public string Notes { get; set; }
        public string Email { get; set; }
        public bool IsRecurring { get; set; }
        public Nullable<int> RecurId { get; set; }
        public string Recur { get; set; }
    
        public virtual AppointmentResult AppointmentResult { get; set; }
    }
}
