//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentResult
    {
        public AppointmentResult()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int ResultID { get; set; }
        public string ResultName { get; set; }
        public bool Active { get; set; }
        public bool IsActionRequired { get; set; }
        public int ResultStatusId { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
