//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentType
    {
        public int ID { get; set; }
        public string TypeName { get; set; }
        public string Color { get; set; }
        public bool Active { get; set; }
        public string Category { get; set; }
        public bool ConfirmationEmail { get; set; }
        public string ConfirmationText { get; set; }
        public string Subject { get; set; }
        public string EmailFromAddress { get; set; }
        public string EmailFromName { get; set; }
        public string Attachment { get; set; }
        public bool OVU { get; set; }
        public string WufooFormKey { get; set; }
        public string MailChimpCampaignId { get; set; }
        public string MailChimpCampaignName { get; set; }
        public int ResultStatusId { get; set; }
    }
}
