//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class apt_rec
    {
        public int apt_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> Arrived_time { get; set; }
        public Nullable<System.DateTime> Seen_nurse_time { get; set; }
        public Nullable<System.DateTime> Seen_dr_time { get; set; }
        public Nullable<System.DateTime> closed_time { get; set; }
        public Nullable<System.DateTime> prescriptprint_time { get; set; }
        public Nullable<System.DateTime> followUp_time { get; set; }
        public Nullable<bool> closed_yn { get; set; }
        public Nullable<System.DateTime> ApptStart { get; set; }
        public Nullable<System.DateTime> ApptEnd { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> AppointmentTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> AllDay { get; set; }
        public Nullable<bool> EmailOnChange { get; set; }
        public Nullable<int> Results { get; set; }
        public string Notes { get; set; }
        public string Email { get; set; }
        public string ActionNeeded { get; set; }
        public int SaleMade_yn { get; set; }
        public string Note { get; set; }
        public bool LabsCheckedIn { get; set; }
        public string ReasonToClose { get; set; }
        public string Clinic { get; set; }
        public int HARep { get; set; }
    }
}
