//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class apt_LisfeStyle
    {
        public int apt_LisfeStyleID { get; set; }
        public int AptID { get; set; }
        public string WaterIntake { get; set; }
        public string WaterIntakeComment { get; set; }
        public string IntakeType { get; set; }
        public string WaterSource { get; set; }
        public string WaterSourceComment { get; set; }
        public string ExerciseFreq { get; set; }
        public string ExerciseFreqComment { get; set; }
        public string ExerciseType { get; set; }
        public string ExerciseTypeCommnet { get; set; }
        public string WorkoutLemgth { get; set; }
        public string WorkoutLemgthComment { get; set; }
        public string SleepQuality { get; set; }
        public string SleepQualityComment { get; set; }
        public Nullable<int> SleepHours { get; set; }
        public Nullable<int> Mealtonin { get; set; }
        public string FruitVeggie { get; set; }
        public string FruitVeggieComment { get; set; }
        public string Diet { get; set; }
        public string DietComment { get; set; }
        public string EnergeyLevel { get; set; }
        public string EnergyComment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public int EnteredBy { get; set; }
    }
}
