//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class apt_FollowUp_types
    {
        public int FollowUp_Type_ID { get; set; }
        public string FollowUp_Type_Desc { get; set; }
        public Nullable<bool> Viewable_YN { get; set; }
        public Nullable<bool> ConsultType_YN { get; set; }
        public Nullable<bool> FollowUpType_YN { get; set; }
        public bool TicketType_YN { get; set; }
        public bool Appointment { get; set; }
        public bool StaffTicketType_YN { get; set; }
        public string CustomPage { get; set; }
        public string CustomHeader { get; set; }
        public string CustomParams { get; set; }
        public bool ChangeColor { get; set; }
        public int DepartmentID { get; set; }
    }
}
