//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class apt_Symtpoms
    {
        public int apt_SymtpomsID { get; set; }
        public int AptID { get; set; }
        public int SymptomID { get; set; }
        public int Priority { get; set; }
        public string dir { get; set; }
        public System.DateTime DateEntered { get; set; }
        public int EnteredBy { get; set; }
        public Nullable<bool> Resolved { get; set; }
    }
}
