//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class apt_Misc
    {
        public int apt_MiscID { get; set; }
        public int AptID { get; set; }
        public bool NewMedicationsYN { get; set; }
        public string NewMedsNames { get; set; }
        public bool NewIllness { get; set; }
        public string IllnessNames { get; set; }
        public string LastPhysical { get; set; }
        public string LastPap { get; set; }
        public string LastMammo { get; set; }
        public string LastProstate { get; set; }
        public string RealizeGoals { get; set; }
        public string HappyProgram { get; set; }
        public string Other { get; set; }
        public string SubjNote { get; set; }
        public System.DateTime DateEntered { get; set; }
        public int EnteredBy { get; set; }
    }
}
