//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class apt_BloodWork
    {
        public int apt_BloodWorkID { get; set; }
        public int AptID { get; set; }
        public bool Fasting { get; set; }
        public string FastingComment { get; set; }
        public bool Creams { get; set; }
        public string CreamComment { get; set; }
        public bool DHEA { get; set; }
        public string DHEAComment { get; set; }
        public bool Pregenolone { get; set; }
        public string PregenoloneAMPM { get; set; }
        public string PregenoloneComment { get; set; }
        public Nullable<bool> Anastrozole { get; set; }
        public string AnastrozoleComment { get; set; }
        public Nullable<bool> Testosterone { get; set; }
        public string TestosteroneComment { get; set; }
        public System.DateTime DateEntered { get; set; }
        public int EnteredBy { get; set; }
    }
}
