//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTicket
    {
        public int AutoTicketID { get; set; }
        public string AutoticketName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public int FollowUp_Type_ID { get; set; }
        public int Assigned { get; set; }
        public int DeptAssign { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> LastSent { get; set; }
        public int CreatedID { get; set; }
        public int Frequency { get; set; }
        public string FrequencyType { get; set; }
    }
}
