//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoshipProduct
    {
        public AutoshipProduct()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.ProfileItems = new HashSet<ProfileItem>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal AutoshipPrice { get; set; }
        public bool Active { get; set; }
        public string QBId { get; set; }
        public int GroupID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<bool> Viewable { get; set; }
        public bool Reviewed { get; set; }
        public string Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string Sku { get; set; }
        public Nullable<bool> Bundle { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<ProfileItem> ProfileItems { get; set; }
    }
}
