//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTicketAlert
    {
        public int AlertID { get; set; }
        public string TestName { get; set; }
        public string MaleMinValue { get; set; }
        public string MaleMaxValue { get; set; }
        public string FemaleMin { get; set; }
        public string FemaleMax { get; set; }
        public Nullable<bool> NoTicket { get; set; }
    }
}
