//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoship_Discounts
    {
        public int DiscountID { get; set; }
        public string DiscountName { get; set; }
        public Nullable<decimal> Dollar { get; set; }
        public Nullable<decimal> Percent { get; set; }
    }
}
