//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallBackRespons
    {
        public int CallBackResponseID { get; set; }
        public int PatientID { get; set; }
        public int CallBackID { get; set; }
        public int AptID { get; set; }
        public int CallBackQuestionID { get; set; }
        public string Response { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime DateEntered { get; set; }
    }
}
