//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Callbacks_old
    {
        public int CallID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string ReasonForCallBack { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public string VisitDate { get; set; }
        public bool Contact { get; set; }
    }
}
