//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_log_tbl
    {
        public int LogID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogEntry { get; set; }
        public Nullable<bool> Viewable_YN { get; set; }
        public Nullable<int> EnteredBy { get; set; }
    }
}
