//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confirm
    {
        public int ConfirmID { get; set; }
        public Nullable<int> CallbackID { get; set; }
        public Nullable<System.DateTime> DateOfCall { get; set; }
        public Nullable<System.DateTime> TimeOfCall { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Caller { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    }
}
