//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_tbl_archive
    {
        public int ContactID_Archive { get; set; }
        public int ContactID { get; set; }
        public Nullable<System.DateTime> ContactDateEntered { get; set; }
        public System.DateTime ContactArcvhiveDate { get; set; }
        public Nullable<int> AptType { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<bool> ReqsFollow_YN { get; set; }
        public string FollowUpBody { get; set; }
        public string MessageBody { get; set; }
        public Nullable<int> FollowUp_Staff { get; set; }
        public Nullable<System.DateTime> FollowUp_Date { get; set; }
        public Nullable<int> FollowUp_Category { get; set; }
        public Nullable<System.DateTime> FollowUp_ActualDate { get; set; }
        public Nullable<bool> FollowUP_Completed { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<int> Apt_ID { get; set; }
        public Nullable<int> FollowUp_ID { get; set; }
    }
}
