//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Type_tbl
    {
        public int AptTypeID { get; set; }
        public string AptTypeDesc { get; set; }
        public Nullable<bool> Viewable_yn { get; set; }
    }
}
