//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Status
    {
        public CRM_Status()
        {
            this.CRM_Prospects = new HashSet<CRM_Prospects>();
        }
    
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public bool Active_YN { get; set; }
    
        public virtual ICollection<CRM_Prospects> CRM_Prospects { get; set; }
    }
}
