//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_MarketingSource_Campaigns
    {
        public int MarketingSource_CampaignID { get; set; }
        public int MarketingSourceID { get; set; }
        public int CampaignID { get; set; }
    
        public virtual CRM_Campaigns CRM_Campaigns { get; set; }
        public virtual CRM_MarketingSources CRM_MarketingSources { get; set; }
    }
}
