//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Events
    {
        public CRM_Events()
        {
            this.CRM_Attendees = new HashSet<CRM_Attendees>();
            this.CRM_Registrants = new HashSet<CRM_Registrants>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Venue { get; set; }
        public string Notes { get; set; }
        public int CampaignID { get; set; }
        public string Location { get; set; }
        public string EventLength { get; set; }
        public string Walkins { get; set; }
        public Nullable<int> Appointments { get; set; }
        public Nullable<int> Callbacks { get; set; }
        public Nullable<int> OverallPerformance { get; set; }
        public Nullable<int> FacilityInteriorExterior { get; set; }
        public Nullable<int> VenueQuality { get; set; }
        public Nullable<int> Parking { get; set; }
        public Nullable<int> AudienceReaction { get; set; }
        public Nullable<int> AudienceQuality { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<CRM_Attendees> CRM_Attendees { get; set; }
        public virtual CRM_Campaigns CRM_Campaigns { get; set; }
        public virtual ICollection<CRM_Registrants> CRM_Registrants { get; set; }
    }
}
