//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Campaigns
    {
        public CRM_Campaigns()
        {
            this.CRM_Events = new HashSet<CRM_Events>();
            this.CRM_MarketingActivity = new HashSet<CRM_MarketingActivity>();
            this.CRM_MarketingSource_Campaigns = new HashSet<CRM_MarketingSource_Campaigns>();
        }
    
        public int CampaignID { get; set; }
        public string CampaignName { get; set; }
        public Nullable<decimal> MarketingBudget { get; set; }
        public int CampaignType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string MarketingSources { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<CRM_Events> CRM_Events { get; set; }
        public virtual ICollection<CRM_MarketingActivity> CRM_MarketingActivity { get; set; }
        public virtual ICollection<CRM_MarketingSource_Campaigns> CRM_MarketingSource_Campaigns { get; set; }
    }
}
