//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_MarketingActivity
    {
        public int MarketingActivityID { get; set; }
        public int SourceID { get; set; }
        public string SourceType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Notes { get; set; }
        public int CapmpaignID { get; set; }
        public Nullable<decimal> Money_Spent { get; set; }
    
        public virtual CRM_Campaigns CRM_Campaigns { get; set; }
        public virtual CRM_MarketingSources CRM_MarketingSources { get; set; }
    }
}
