//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentStaff
    {
        public int DepartmentStaffID { get; set; }
        public int StaffID { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
