//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis_tbl
    {
        public int Diagnosis_ID { get; set; }
        public string Diag_Title { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ICD9_Code { get; set; }
        public Nullable<bool> Viewable_YN { get; set; }
    }
}
