//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictation_Diagnosis
    {
        public int DiagnosisID { get; set; }
        public string DiagnosisName { get; set; }
        public string DiagnosisDescrip { get; set; }
        public string ICDCode { get; set; }
        public string KeyWords { get; set; }
        public bool Viewable_YN { get; set; }
    }
}
