//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictation_Plan
    {
        public int PlanID { get; set; }
        public string PlanName { get; set; }
        public string PlanDescrip { get; set; }
        public string Category { get; set; }
        public string KeyWords { get; set; }
        public bool Viewable_YN { get; set; }
    }
}
