//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalLabList
    {
        public int ExternalLabListID { get; set; }
        public string ExternaLabName { get; set; }
        public Nullable<int> PanelID { get; set; }
    }
}
