//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalLab
    {
        public int ExternalLabID { get; set; }
        public int ProviderID { get; set; }
        public int LabID { get; set; }
        public string Patient { get; set; }
        public System.DateTime DateOrdered { get; set; }
    }
}
