//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalItem
    {
        public int GoalItemID { get; set; }
        public string Tag { get; set; }
        public string DisplayName { get; set; }
        public string TextBoxName { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> ProviderID { get; set; }
    }
}
