//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRange
    {
        public int GroupRangeID { get; set; }
        public int GroupID { get; set; }
        public double HighRange { get; set; }
        public double LowRange { get; set; }
    }
}
