//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitalization
    {
        public int HospitalizationID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> HospDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
