//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class intake_form_hormone_review
    {
        public int hormone_review_id { get; set; }
        public Nullable<int> master_form_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<System.DateTime> f_date_of_last_period { get; set; }
        public string f_birth_ctrl_method { get; set; }
        public Nullable<bool> f_pregnant_YN { get; set; }
        public Nullable<System.DateTime> f_date_of_last_pap_test { get; set; }
        public string f_last_pap_test_result { get; set; }
        public Nullable<System.DateTime> f_date_of_last_mammogram { get; set; }
        public string f_last_mammogram_result { get; set; }
        public Nullable<System.DateTime> f_date_of_menopause { get; set; }
        public Nullable<bool> f_abnormal_pap_YN { get; set; }
        public Nullable<System.DateTime> f_abnormal_pap_date { get; set; }
        public Nullable<bool> f_hot_flashes_YN { get; set; }
        public Nullable<bool> f_night_sweats_YN { get; set; }
        public Nullable<bool> f_leak_urine_YN { get; set; }
        public Nullable<bool> f_fibrocystic_breasts_YN { get; set; }
        public Nullable<bool> f_sleep_problems_YN { get; set; }
        public Nullable<bool> f_vaginal_dryness_pain_YN { get; set; }
        public Nullable<bool> f_loss_of_interest_in_sex_YN { get; set; }
        public Nullable<bool> f_irregular_periods_YN { get; set; }
        public Nullable<bool> f_spotting_after_menopause_YN { get; set; }
        public Nullable<bool> f_mood_swings_YN { get; set; }
        public Nullable<bool> f_pms_YN { get; set; }
        public Nullable<bool> f_bloating_late_in_cycle_YN { get; set; }
        public Nullable<bool> f_migraines_late_in_cycle_YN { get; set; }
        public Nullable<bool> f_cravings_sugar_chocalate_YN { get; set; }
        public Nullable<bool> f_pcos_YN { get; set; }
        public Nullable<bool> f_acne_YN { get; set; }
        public Nullable<bool> f_facial_hair_YN { get; set; }
        public Nullable<bool> f_lack_of_periods_YN { get; set; }
        public Nullable<bool> f_problems_with_infertility_YN { get; set; }
        public Nullable<bool> f_ovarian_cysts_YN { get; set; }
        public Nullable<bool> f_uterine_fibroid_YN { get; set; }
        public Nullable<bool> f_cramps_clots_with_period_YN { get; set; }
        public Nullable<bool> f_increased_fat_hips_thighs_YN { get; set; }
        public Nullable<bool> f_endometriosis_YN { get; set; }
        public Nullable<bool> f_painful_sex_YN { get; set; }
        public Nullable<bool> f_painful_periods_YN { get; set; }
        public Nullable<bool> f_vaginal_irritation_YN { get; set; }
        public Nullable<bool> f_unusual_vaginal_discharge_YN { get; set; }
        public Nullable<System.DateTime> m_date_of_last_prostate_exam { get; set; }
        public Nullable<bool> m_lowered_interest_in_sex_YN { get; set; }
        public Nullable<bool> m_cannot_maintain_erecetion_YN { get; set; }
        public Nullable<bool> m_erection_less_firm_YN { get; set; }
        public Nullable<bool> m_enlarged_prostate_YN { get; set; }
        public Nullable<bool> m_slowing_urinary_stream_YN { get; set; }
        public Nullable<bool> m_night_time_urination_YN { get; set; }
        public Nullable<bool> m_difficulty_initiating_urine_stream_YN { get; set; }
        public Nullable<bool> m_bladder_not_emptying_YN { get; set; }
        public Nullable<bool> m_premature_ejaculation_YN { get; set; }
        public Nullable<bool> dry_hair_YN { get; set; }
        public Nullable<bool> infertility_YN { get; set; }
        public Nullable<bool> migraines_YN { get; set; }
        public Nullable<bool> losing_hair_YN { get; set; }
        public Nullable<bool> constipation_YN { get; set; }
        public Nullable<bool> fluid_retention_YN { get; set; }
        public Nullable<bool> crave_caffeine_YN { get; set; }
        public Nullable<bool> dry_coarse_skin_YN { get; set; }
        public Nullable<bool> diets_dont_work_YN { get; set; }
        public Nullable<bool> cold_hands_feet_YN { get; set; }
        public Nullable<bool> elevated_cholesterol_YN { get; set; }
        public Nullable<bool> low_body_temp_YN { get; set; }
        public Nullable<bool> fatigue_exhaustion_YN { get; set; }
        public Nullable<bool> decreased_memory_YN { get; set; }
        public Nullable<bool> brittle_nails_YN { get; set; }
        public Nullable<bool> unable_to_lose_weight_YN { get; set; }
        public Nullable<bool> daytime_drowsiness_YN { get; set; }
        public Nullable<bool> foggy_mind_YN { get; set; }
        public Nullable<bool> depression_anxiety_YN { get; set; }
        public Nullable<bool> low_ambition_motivation_YN { get; set; }
        public Nullable<bool> decreased_concentration_YN { get; set; }
        public Nullable<bool> fibromyalgia_chronic_fatigue_YN { get; set; }
        public Nullable<bool> feel_cold_YN { get; set; }
        public Nullable<bool> palpitations_YN { get; set; }
        public Nullable<bool> salt_craving_YN { get; set; }
        public Nullable<bool> muscle_tension_YN { get; set; }
        public Nullable<bool> easily_frustrated_YN { get; set; }
        public Nullable<bool> poor_stress_tolerance_YN { get; set; }
        public Nullable<bool> sugar_craving_YN { get; set; }
        public Nullable<bool> panic_attacks_YN { get; set; }
        public Nullable<bool> excessive_hungar_YN { get; set; }
        public Nullable<bool> prone_to_infection_YN { get; set; }
        public Nullable<bool> low_blood_pressure_YN { get; set; }
        public Nullable<bool> light_headed_standing_up_YN { get; set; }
        public Nullable<bool> racing_mind_no_sleep_YN { get; set; }
        public Nullable<bool> sluggish_am_slow_starter_YN { get; set; }
        public Nullable<bool> need_sunglasses_in_sunlight_YN { get; set; }
        public Nullable<bool> low_back_pain_with_stress_YN { get; set; }
        public Nullable<bool> cannot_skip_meals_YN { get; set; }
        public Nullable<bool> headache_when_missed_meal_YN { get; set; }
        public Nullable<bool> crave_sugar_carbs_YN { get; set; }
        public Nullable<bool> low_energy_relieved_with_food_YN { get; set; }
        public Nullable<bool> shake_weak_YN { get; set; }
        public Nullable<bool> jittery_irratable_YN { get; set; }
        public Nullable<bool> high_and_low_moods_YN { get; set; }
        public Nullable<bool> sluggish_and_high_energy_YN { get; set; }
        public Nullable<bool> high_blood_pressure_YN { get; set; }
        public Nullable<bool> high_cholesterol_YN { get; set; }
        public Nullable<bool> mid_afternoon_drowsiness_YN { get; set; }
        public Nullable<bool> increased_fat_abdomen_YN { get; set; }
        public Nullable<bool> inflammation_bursitis_YN { get; set; }
        public Nullable<bool> fluid_retention_puffy_extremities_YN { get; set; }
        public Nullable<bool> decreased_stamina_YN { get; set; }
        public Nullable<bool> decreased_endurance_YN { get; set; }
        public Nullable<bool> run_out_of_breath_YN { get; set; }
        public Nullable<bool> easily_exhausted_YN { get; set; }
        public Nullable<bool> decreased_desire_exercise_YN { get; set; }
        public Nullable<bool> dry_skin_YN { get; set; }
        public Nullable<bool> thin_lips_YN { get; set; }
        public Nullable<bool> graying_hair_YN { get; set; }
        public Nullable<bool> skin_blemishes_YN { get; set; }
        public Nullable<bool> tendency_bruising_YN { get; set; }
        public Nullable<bool> thinned_skin_YN { get; set; }
        public Nullable<bool> thinning_hair_YN { get; set; }
        public Nullable<bool> wrinkling_skin_YN { get; set; }
        public Nullable<bool> sagging_skin_YN { get; set; }
        public Nullable<bool> osteoporosis_YN { get; set; }
        public Nullable<bool> aches_pains_YN { get; set; }
        public Nullable<bool> loss_of_strength_YN { get; set; }
        public Nullable<bool> body_joints_YN { get; set; }
        public Nullable<bool> thinning_muscles_YN { get; set; }
        public Nullable<bool> loss_of_esteem_YN { get; set; }
        public Nullable<bool> feeling_hopeless_YN { get; set; }
        public Nullable<bool> feeling_defeated_YN { get; set; }
        public Nullable<bool> feeling_apathy_YN { get; set; }
        public Nullable<bool> loss_of_confidence_YN { get; set; }
        public Nullable<bool> vision_deteriorating_YN { get; set; }
        public Nullable<bool> hearing_deteriorating_YN { get; set; }
        public Nullable<bool> memory_deteriorating_YN { get; set; }
        public Nullable<bool> balance_deteriorating_YN { get; set; }
        public Nullable<bool> coordination_deteriorating_YN { get; set; }
        public Nullable<bool> sense_of_powerlessness_YN { get; set; }
        public Nullable<bool> decreased_sense_of_well_being_YN { get; set; }
        public Nullable<bool> indigestion_YN { get; set; }
        public Nullable<bool> feel_full_faster_YN { get; set; }
        public Nullable<bool> slower_digestion_YN { get; set; }
        public Nullable<bool> eat_less_meals_YN { get; set; }
        public Nullable<bool> fullness_persists_after_meal_YN { get; set; }
        public Nullable<bool> burping_belching_after_meal_YN { get; set; }
        public Nullable<bool> decreased_sense_of_taste_smell_YN { get; set; }
        public string specific_diet { get; set; }
        public Nullable<bool> diet_is_successful_YN { get; set; }
        public string past_successful_diets { get; set; }
        public string stess_level { get; set; }
        public string stress_how_long { get; set; }
        public string stress_expect_to_last { get; set; }
        public Nullable<bool> stress_solution_YN { get; set; }
        public Nullable<bool> need_help_with_stress_YN { get; set; }
        public string exercise_type { get; set; }
        public string exercise_length_of_session { get; set; }
        public string exercise_frequency { get; set; }
        public Nullable<bool> early_morning_waking_YN { get; set; }
        public Nullable<bool> trouble_getting_to_sleep_YN { get; set; }
        public Nullable<bool> sleep_not_restful_YN { get; set; }
        public Nullable<bool> sleep_toss_and_turn_YN { get; set; }
        public Nullable<bool> daytime_drowsiness_sleepiness_YN { get; set; }
        public Nullable<bool> sleep_feeling_smothered_choke_YN { get; set; }
        public Nullable<bool> heaving_snoring_stop_breathing_YN { get; set; }
        public Nullable<bool> work_night_shift_YN { get; set; }
        public string night_shifts_per_week { get; set; }
        public string exercise_type_other { get; set; }
    }
}
