//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class intake_form_prescriptions
    {
        public int prescription_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> drug_id { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public string dosage { get; set; }
        public string medication { get; set; }
    }
}
