//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class intake_form_surgeries
    {
        public int surgeries_id { get; set; }
        public Nullable<int> master_form_id { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<bool> hysterectomy_YN { get; set; }
        public Nullable<System.DateTime> hysterectomy_date { get; set; }
        public string hysterectomy_reason { get; set; }
        public Nullable<bool> appendix_YN { get; set; }
        public Nullable<System.DateTime> appendix_date { get; set; }
        public Nullable<bool> tonsils_YN { get; set; }
        public Nullable<System.DateTime> tonsils_date { get; set; }
        public Nullable<bool> gall_bladder_YN { get; set; }
        public Nullable<System.DateTime> gall_bladder_date { get; set; }
        public Nullable<bool> colon_YN { get; set; }
        public Nullable<System.DateTime> colon_date { get; set; }
        public string colon_reason { get; set; }
        public Nullable<bool> prostate_YN { get; set; }
        public Nullable<System.DateTime> prostate_date { get; set; }
        public string prostate_reason { get; set; }
        public Nullable<bool> orthopedic_YN { get; set; }
        public Nullable<System.DateTime> orthopedic_date { get; set; }
        public string orthopedic_reason { get; set; }
        public Nullable<bool> heart_YN { get; set; }
        public Nullable<System.DateTime> heart_date { get; set; }
        public string heart_reason { get; set; }
        public Nullable<bool> thyroid_YN { get; set; }
        public Nullable<System.DateTime> thyroid_date { get; set; }
        public string thyroid_reason { get; set; }
        public Nullable<bool> breast_YN { get; set; }
        public Nullable<System.DateTime> breast_date { get; set; }
        public string breast_reason { get; set; }
        public Nullable<bool> stomach_YN { get; set; }
        public Nullable<System.DateTime> stomach_date { get; set; }
        public string stomach_reason { get; set; }
        public string other_surgeries { get; set; }
        public Nullable<int> patient_id { get; set; }
    }
}
