//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class intake_form_allergies
    {
        public int allergies_id { get; set; }
        public Nullable<int> master_form_id { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<bool> drug_or_med_allergy_YN { get; set; }
        public string drug_or_med_allergy { get; set; }
        public Nullable<bool> food_allergy_YN { get; set; }
        public string food_allergy { get; set; }
        public Nullable<int> patient_id { get; set; }
    }
}
