//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class intake_form_symptoms
    {
        public int symptoms_id { get; set; }
        public Nullable<int> master_form_id { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<bool> chest_pain_YN { get; set; }
        public Nullable<bool> nose_bleeds_YN { get; set; }
        public Nullable<bool> abdominal_pain_YN { get; set; }
        public Nullable<bool> difficulty_swallowing_YN { get; set; }
        public Nullable<bool> kidney_pain_YN { get; set; }
        public Nullable<bool> change_in_headaches_YN { get; set; }
        public Nullable<bool> bone_pain_YN { get; set; }
        public Nullable<bool> excessive_thirst_YN { get; set; }
        public Nullable<bool> change_in_bowel_habit_YN { get; set; }
        public Nullable<bool> unexpected_weight_loss_YN { get; set; }
        public Nullable<bool> blood_in_sputum_YN { get; set; }
        public Nullable<bool> shortness_of_breath_YN { get; set; }
        public Nullable<bool> acid_reflux_YN { get; set; }
        public Nullable<bool> loss_of_appetite_YN { get; set; }
        public Nullable<bool> blood_in_urine_YN { get; set; }
        public Nullable<bool> double_vision_YN { get; set; }
        public Nullable<bool> unusual_bruising_YN { get; set; }
        public Nullable<bool> rapid_heart_beat_YN { get; set; }
        public Nullable<bool> faint_collapse_YN { get; set; }
        public Nullable<bool> swollen_ankels_YN { get; set; }
        public Nullable<bool> black_tarry_stools_YN { get; set; }
        public Nullable<bool> persistent_nausea_YN { get; set; }
        public Nullable<bool> urgent_urination_YN { get; set; }
        public Nullable<bool> dizzy_spinning_YN { get; set; }
        public Nullable<bool> prolonged_bleeding_YN { get; set; }
        public Nullable<bool> unusual_cough_YN { get; set; }
        public Nullable<bool> leg_pain_walking_YN { get; set; }
        public Nullable<bool> excessive_snoring_YN { get; set; }
        public Nullable<bool> blood_in_stool_YN { get; set; }
        public Nullable<bool> mood_swings_YN { get; set; }
        public Nullable<bool> frequent_urination_YN { get; set; }
        public Nullable<bool> eye_pain_YN { get; set; }
        public Nullable<bool> bloated_YN { get; set; }
        public string other_symptoms { get; set; }
        public Nullable<int> patient_id { get; set; }
    }
}
