//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class intake_form_goals
    {
        public int goal_id { get; set; }
        public Nullable<int> master_form_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<bool> balance_hormones_YN { get; set; }
        public Nullable<bool> start_hormones_YN { get; set; }
        public Nullable<bool> improve_energy_YN { get; set; }
        public Nullable<bool> feel_better_YN { get; set; }
        public Nullable<bool> feel_stronger_YN { get; set; }
        public Nullable<bool> improve_sleep_YN { get; set; }
        public Nullable<bool> eliminate_hot_flashes_YN { get; set; }
        public Nullable<bool> eliminate_prescriptions_YN { get; set; }
        public Nullable<bool> weight_loss_YN { get; set; }
        public Nullable<bool> stabalize_PMS_YN { get; set; }
        public Nullable<bool> stop_hair_loss_YN { get; set; }
        public Nullable<bool> sense_of_well_being_YN { get; set; }
        public Nullable<bool> enhance_immune_sys_YN { get; set; }
        public Nullable<bool> less_pain_YN { get; set; }
        public string less_pain_where { get; set; }
        public Nullable<bool> improve_libido_YN { get; set; }
        public Nullable<bool> improve_sex_life_YN { get; set; }
        public Nullable<bool> improve_muscle_YN { get; set; }
        public Nullable<bool> improve_memory_YN { get; set; }
        public Nullable<bool> bladder_control_YN { get; set; }
        public Nullable<bool> improve_skin_YN { get; set; }
        public Nullable<bool> better_stamina_YN { get; set; }
        public Nullable<bool> general_wellness_YN { get; set; }
        public Nullable<bool> reduce_stress_YN { get; set; }
        public Nullable<bool> improve_metabolism_YN { get; set; }
        public string other { get; set; }
    }
}
