//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal_Main
    {
        public int Jrn_id { get; set; }
        public string Jrn_title { get; set; }
        public string Jrn_body { get; set; }
        public Nullable<System.DateTime> Jrn_created { get; set; }
        public Nullable<System.DateTime> Jrn_last_edited { get; set; }
        public Nullable<int> Jrn_created_by { get; set; }
        public Nullable<bool> Active_YN { get; set; }
        public string External_link { get; set; }
    }
}
