//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_NotesAndCommentsSegments
    {
        public int ID { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string TableName { get; set; }
        public int TableRowID { get; set; }
        public Nullable<int> SetID { get; set; }
        public string CommentSource { get; set; }
        public string Comment { get; set; }
    }
}
