//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_GuarantorSegments
    {
        public int ID { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int PatientID { get; set; }
        public int SetID { get; set; }
        public string GuarantorNameLastName { get; set; }
        public string GuarantorNameFirstName { get; set; }
        public string GuarantorNameMiddleName { get; set; }
        public string GuarantorNameSuffix { get; set; }
        public string GuarantorNamePrefix { get; set; }
        public string GuarantorNameDegree { get; set; }
        public string GuarantorAddressStreetAddress { get; set; }
        public string GuarantorAddressOtherDesignation { get; set; }
        public string GuarantorAddressCity { get; set; }
        public string GuarantorAddressState { get; set; }
        public string GuarantorAddressZipCode { get; set; }
        public string GuarantorAddressCountry { get; set; }
        public string GuarantorHomePhone { get; set; }
        public System.DateTime GuarantorBirthDateTime { get; set; }
        public string GuarantorSex { get; set; }
    
        public virtual lab_Patients lab_Patients { get; set; }
    }
}
