//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_Messages
    {
        public lab_Messages()
        {
            this.lab_AcknowledgementSegments = new HashSet<lab_AcknowledgementSegments>();
            this.lab_Patients = new HashSet<lab_Patients>();
        }
    
        public int ID { get; set; }
        public System.DateTime LastChanged { get; set; }
        public string SendingApp { get; set; }
        public string SendingFacility { get; set; }
        public string ReceivingApp { get; set; }
        public string ReceivingFacility { get; set; }
        public System.DateTime MessageDateTimeSenderCreated { get; set; }
        public string MessageType { get; set; }
        public string MessageControlID { get; set; }
        public string ProcessingID { get; set; }
        public string VersionID { get; set; }
        public string TotalMessage { get; set; }
    
        public virtual ICollection<lab_AcknowledgementSegments> lab_AcknowledgementSegments { get; set; }
        public virtual ICollection<lab_Patients> lab_Patients { get; set; }
    }
}
