//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_CommonOrderSegments
    {
        public lab_CommonOrderSegments()
        {
            this.lab_OrderSegmentDetails = new HashSet<lab_OrderSegmentDetails>();
        }
    
        public int ID { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int PatientID { get; set; }
        public string OrderControl { get; set; }
        public string PlacerOrderNumber { get; set; }
        public string FillerOrderNumber { get; set; }
        public string OrderStatus { get; set; }
        public string OrderingProviderIDNumber { get; set; }
        public string OrderingProviderLastName { get; set; }
        public string OrderingProviderFirstName { get; set; }
        public string OrderingProviderMiddleName { get; set; }
        public string OrderingProviderSuffix { get; set; }
        public string OrderingProviderPrefix { get; set; }
        public string OrderingProviderDegree { get; set; }
        public bool InActive { get; set; }
    
        public virtual lab_Patients lab_Patients { get; set; }
        public virtual ICollection<lab_OrderSegmentDetails> lab_OrderSegmentDetails { get; set; }
    }
}
