//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_DiagnosisSegments
    {
        public int ID { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int OrderSegmentDetailID { get; set; }
        public int SetID { get; set; }
        public string DiagnosisCodingMethod { get; set; }
        public string DiagnosisCode { get; set; }
    
        public virtual lab_OrderSegmentDetails lab_OrderSegmentDetails { get; set; }
    }
}
