//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_InsuranceSegments
    {
        public int ID { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int PatientID { get; set; }
        public int SetID { get; set; }
        public string InsurancePlanID { get; set; }
        public string InsuranceCompanyID { get; set; }
        public string InsuranceCompanyName { get; set; }
        public string InsuranceCompanyStreetAddress { get; set; }
        public string InsuranceCompanyOtherDesignation { get; set; }
        public string InsuranceCompanyCity { get; set; }
        public string InsuranceCompanyState { get; set; }
        public string InsuranceCompanyZipCode { get; set; }
        public string InsuranceCompanyCountry { get; set; }
        public string InsuranceCompanyPhone { get; set; }
        public string GroupNumber { get; set; }
        public string InsuredsGroupEmpName { get; set; }
        public string NameOfInsuredLastName { get; set; }
        public string NameOfInsuredFirstName { get; set; }
        public string NameOfInsuredMiddleName { get; set; }
        public string NameOfInsuredSuffix { get; set; }
        public string NameOfInsuredPrefix { get; set; }
        public string NameOfInsuredDegree { get; set; }
        public string InsuredsRelationshipToPatient { get; set; }
        public Nullable<System.DateTime> InsuredsDateOfBirth { get; set; }
        public string InsuredsAddressStreetAddress { get; set; }
        public string InsuredsAddressOtherDesignation { get; set; }
        public string InsuredsAddressCity { get; set; }
        public string InsuredsAddressState { get; set; }
        public string InsuredsAddressZipCode { get; set; }
        public string InsuredsAddressCountry { get; set; }
        public string CompanyPlanCode { get; set; }
        public string PolicyNumber { get; set; }
        public string InsuredsEmployerAddressStreetAddress { get; set; }
        public string InsuredsEmployerAddressOtherDesignation { get; set; }
        public string InsuredsEmployerAddressCity { get; set; }
        public string InsuredsEmployerAddressState { get; set; }
        public string InsuredsEmployerAddressZipCode { get; set; }
        public string InsuredsEmployerAddressCountry { get; set; }
        public string CoverageType { get; set; }
    
        public virtual lab_Patients lab_Patients { get; set; }
    }
}
