//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabLog
    {
        public int LabLogID { get; set; }
        public string LabName { get; set; }
        public System.DateTime DateImported { get; set; }
        public string PatientName { get; set; }
        public string Birthday { get; set; }
    }
}
