//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabRequests_Requests
    {
        public int LabRequests_RequestID { get; set; }
        public int PatientID { get; set; }
        public bool Fasting { get; set; }
        public System.DateTime StartRange { get; set; }
        public Nullable<System.DateTime> EndRange { get; set; }
    }
}
