//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabRequest_Panels
    {
        public int LabRequest_PanelID { get; set; }
        public string PanelName { get; set; }
        public Nullable<bool> Active_YN { get; set; }
    }
}
