//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabReports_Data
    {
        public int DataID { get; set; }
        public int PatientID { get; set; }
        public Nullable<int> PanelID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> TriggerID { get; set; }
        public string GroupTitle { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> ReceivedDateTime { get; set; }
        public Nullable<System.DateTime> ReportedDateTime { get; set; }
        public string Description { get; set; }
        public Nullable<double> ObservationValue { get; set; }
        public Nullable<System.DateTime> ObservationDateTIme { get; set; }
        public Nullable<double> LongevityLowValue { get; set; }
        public Nullable<double> LongevityHighValue { get; set; }
        public string NormalText { get; set; }
        public string LowText { get; set; }
        public string HighText { get; set; }
    }
}
