//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabReports_Triggers
    {
        public LabReports_Triggers()
        {
            this.LabReports_Conditions = new HashSet<LabReports_Conditions>();
            this.LabReports_TriggersGroups = new HashSet<LabReports_TriggersGroups>();
        }
    
        public int TriggerID { get; set; }
        public string TriggerName { get; set; }
        public string TriggerDescription { get; set; }
        public int PanelID { get; set; }
    
        public virtual ICollection<LabReports_Conditions> LabReports_Conditions { get; set; }
        public virtual LabReports_Panels LabReports_Panels { get; set; }
        public virtual ICollection<LabReports_TriggersGroups> LabReports_TriggersGroups { get; set; }
    }
}
