//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabReports_TriggersGroups
    {
        public int TriggerGroupID { get; set; }
        public int TriggerID { get; set; }
        public int GroupID { get; set; }
    
        public virtual LabReports_Groups LabReports_Groups { get; set; }
        public virtual LabReports_Triggers LabReports_Triggers { get; set; }
    }
}
