//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabReports_Panels
    {
        public LabReports_Panels()
        {
            this.LabReports_Groups = new HashSet<LabReports_Groups>();
            this.LabReports_Triggers = new HashSet<LabReports_Triggers>();
        }
    
        public int PanelID { get; set; }
        public string PanelName { get; set; }
        public string PanelDescrip { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<LabReports_Groups> LabReports_Groups { get; set; }
        public virtual ICollection<LabReports_Triggers> LabReports_Triggers { get; set; }
    }
}
