//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabReports_ConditionDetails
    {
        public int ConditionDetailID { get; set; }
        public int GroupID { get; set; }
        public string Operator { get; set; }
        public double Value { get; set; }
        public string AndOperator { get; set; }
        public Nullable<double> AndValue { get; set; }
        public int ConditionID { get; set; }
        public bool Valid { get; set; }
    
        public virtual LabReports_Conditions LabReports_Conditions { get; set; }
        public virtual LabReports_Groups LabReports_Groups { get; set; }
    }
}
