//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabReports_Conditions
    {
        public LabReports_Conditions()
        {
            this.LabReports_ConditionDetails = new HashSet<LabReports_ConditionDetails>();
        }
    
        public int ConditionID { get; set; }
        public string ConditionName { get; set; }
        public string ConditionDescrip { get; set; }
        public string Sex { get; set; }
        public int TriggerID { get; set; }
    
        public virtual ICollection<LabReports_ConditionDetails> LabReports_ConditionDetails { get; set; }
        public virtual LabReports_Triggers LabReports_Triggers { get; set; }
    }
}
