//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabScehdule_Groups
    {
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string Descrip { get; set; }
        public string SearchText { get; set; }
        public string FullTestName { get; set; }
        public Nullable<int> Male { get; set; }
        public Nullable<int> Female { get; set; }
        public Nullable<bool> InRange { get; set; }
        public Nullable<System.DateTime> LastComplete { get; set; }
        public Nullable<int> Days { get; set; }
    }
}
