//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoMail
    {
        public int NoMailID { get; set; }
        public string PatientName { get; set; }
        public string MessageText { get; set; }
        public bool Complete { get; set; }
        public string Attachment { get; set; }
        public string Subject { get; set; }
    }
}
