//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPackage
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public int RenewalID { get; set; }
        public System.DateTime DateEntered { get; set; }
        public int Duration { get; set; }
        public Nullable<int> MergedPatientID { get; set; }
    }
}
