//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients_CriticalTasks
    {
        public int TaskID { get; set; }
        public int PatientID { get; set; }
        public int TaskTypeID { get; set; }
        public bool Requested { get; set; }
        public bool Received { get; set; }
        public bool Reviewed { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<int> UploadID { get; set; }
    
        public virtual Patients_CriticalTaskType Patients_CriticalTaskType { get; set; }
    }
}
