//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_GoalItems
    {
        public int GoalItemID { get; set; }
        public int GoalTypeID { get; set; }
        public int GoalID { get; set; }
        public int PatientID { get; set; }
        public int Value { get; set; }
        public string Dir { get; set; }
    
        public virtual Patient_GoalItemType Patient_GoalItemType { get; set; }
        public virtual Patient_Goals Patient_Goals { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
