//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientQuestionAnwerSurvey
    {
        public int ID { get; set; }
        public string EntryID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> MergedPatientID { get; set; }
        public Nullable<int> ApptID { get; set; }
        public Nullable<int> PatientID { get; set; }
    
        public virtual PatientQuestionAnwerSurvey PatientQuestionAnwerSurvey1 { get; set; }
        public virtual PatientQuestionAnwerSurvey PatientQuestionAnwerSurvey2 { get; set; }
    }
}
