//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_mrkting_src
    {
        public int SourceTypeID { get; set; }
        public string SourceTypeDesc { get; set; }
        public Nullable<bool> Viewable_YN { get; set; }
    }
}
