//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potential
    {
        public int PotentialID { get; set; }
        public string PotentialFirstName { get; set; }
        public string PotentialLastName { get; set; }
        public string PotentialMiddleInitial { get; set; }
        public string PotentialStreet { get; set; }
        public string PotentialCity { get; set; }
        public string PotentialState { get; set; }
        public string PotentialZip { get; set; }
        public string PotentialPhoneNumber { get; set; }
        public string Source { get; set; }
        public string Guests { get; set; }
        public Nullable<System.DateTime> SeminarDate { get; set; }
        public bool Confirmed { get; set; }
        public bool SignedIn { get; set; }
        public bool SignedUp { get; set; }
        public bool FollowUpLetter { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    }
}
