//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> Writer { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<int> Drug_ID { get; set; }
        public string Drug_Dose { get; set; }
        public string Drug_Dispenses { get; set; }
        public string Drug_NumbRefills { get; set; }
        public Nullable<System.DateTime> Drug_DatePrescibed { get; set; }
        public Nullable<System.DateTime> Drug_EndDate { get; set; }
        public Nullable<bool> Closed_yn { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public Nullable<bool> viewable_yn { get; set; }
        public Nullable<bool> ThirdParty_YN { get; set; }
        public Nullable<bool> RePre_yn { get; set; }
        public Nullable<int> RePre_PreID { get; set; }
        public Nullable<bool> Printed_yn { get; set; }
        public Nullable<int> AptID { get; set; }
        public Nullable<bool> Approved_YN { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public string Notes { get; set; }
    }
}
