//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresscriptionSupp
    {
        public int PresscriptionSuppID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<int> Writer { get; set; }
        public int EnteredBy { get; set; }
        public int ProductID { get; set; }
        public string SuppDose { get; set; }
        public string SuppNumbRefills { get; set; }
        public string SuppDispenses { get; set; }
        public Nullable<System.DateTime> SuppDatePrescibed { get; set; }
        public Nullable<System.DateTime> SuppEndDate { get; set; }
        public Nullable<bool> Closed_yn { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public Nullable<bool> viewable_yn { get; set; }
        public Nullable<bool> RePre_yn { get; set; }
        public Nullable<int> RePre_PreID { get; set; }
        public Nullable<int> AptID { get; set; }
        public Nullable<bool> Approved_YN { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public string Notes { get; set; }
    }
}
