//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocol
    {
        public int Protocol_ID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public string Protocol_Title { get; set; }
        public string Protocol_Desc { get; set; }
        public Nullable<bool> Viewable_YN { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
