//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QB_CreditMemoLine
    {
        public int CreditMemoLineID { get; set; }
        public string TxnID { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<int> TxnNumber { get; set; }
        public string CustomerRefListID { get; set; }
        public string CreditMemoLineType { get; set; }
        public Nullable<int> CreditMemoLineSeqNo { get; set; }
        public string CreditMemoLineTxnLineID { get; set; }
        public string CreditMemoLineItemRefListID { get; set; }
        public string CreditMemoLineItemRefFullName { get; set; }
        public string CreditMemoLineDesc { get; set; }
        public Nullable<decimal> CreditMemoLineQuantity { get; set; }
        public Nullable<System.DateTime> CreditMemoLineServiceDate { get; set; }
        public string CreditMemoLineSalesTaxCodeRefListID { get; set; }
        public Nullable<bool> CreditMemoLineIsTaxable { get; set; }
    }
}
