//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QB_Invoice1
    {
        public System.Guid QBInvID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> IsPaid { get; set; }
        public Nullable<int> IsRecUpdate { get; set; }
    }
}
