//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBEmrSetting
    {
        public int QBEmrSettingsID { get; set; }
        public System.DateTime LastInvoiceCheck { get; set; }
        public int SleepTime { get; set; }
        public Nullable<System.DateTime> LastLabCheck { get; set; }
        public Nullable<System.DateTime> LastApptCallBack { get; set; }
    }
}
