//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recur
    {
        public int RecurID { get; set; }
        public int ApointmentID { get; set; }
        public int DaysInterval { get; set; }
        public System.DateTime StartRecur { get; set; }
        public System.DateTime StopRecur { get; set; }
        public int Range { get; set; }
        public int RecurCount { get; set; }
    }
}
