//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sat_Survey
    {
        public int Sat_ID { get; set; }
        public string Patient_ID { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<int> Sat_Overall { get; set; }
        public Nullable<int> Sat_CustServ { get; set; }
        public Nullable<int> Sat_Progress { get; set; }
        public Nullable<int> Dr_ID { get; set; }
    }
}
