//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminar_list
    {
        public int Seminar_ID { get; set; }
        public Nullable<System.DateTime> Seminar_Date { get; set; }
        public Nullable<System.DateTime> Seminar_time { get; set; }
        public string Seminar_location { get; set; }
        public Nullable<int> Seminar_city { get; set; }
    }
}
