//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharePointPatients
    {
        public int Id { get; set; }
        public int ClinicId { get; set; }
        public int ProviderId { get; set; }
        public Nullable<System.DateTime> StartRange { get; set; }
        public Nullable<System.DateTime> EndRange { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> ApptDuration { get; set; }
        public string Phone { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
