//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialAttentionFlag
    {
        public int SpecialAttentionID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string FlagNotes { get; set; }
        public Nullable<bool> FlagYN { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<int> StaffId { get; set; }
    }
}
