//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusProvider
    {
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public bool Ticket { get; set; }
        public string TicketText { get; set; }
        public bool Active { get; set; }
        public int CalledDays { get; set; }
    }
}
