//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplement_RX
    {
        public int Supp_rx_id { get; set; }
        public Nullable<int> SupplementID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<bool> Expired_YN { get; set; }
        public Nullable<System.DateTime> Date_Expired { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<int> PrescribingDR { get; set; }
        public Nullable<int> DosePerDay { get; set; }
        public Nullable<int> AptID { get; set; }
        public string Notes { get; set; }
    }
}
