//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplement
    {
        public int Supp_id { get; set; }
        public string Supplement_Name { get; set; }
        public Nullable<bool> Viewable_YN { get; set; }
        public Nullable<int> Units_per_container { get; set; }
        public Nullable<System.DateTime> dateentered { get; set; }
        public Nullable<bool> LMC_supplement_yn { get; set; }
    }
}
