//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets_Manage
    {
        public int ProcessID { get; set; }
        public string ProcessName { get; set; }
        public int Interval { get; set; }
        public bool Enabled { get; set; }
        public string Note { get; set; }
    }
}
