//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class train_module
    {
        public int module_id { get; set; }
        public string module_title { get; set; }
        public string module_details { get; set; }
        public string file_location { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public System.DateTime date_created { get; set; }
        public bool active_YN { get; set; }
    }
}
