//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class train_user2profile
    {
        public int user_profile_id { get; set; }
        public int user_id { get; set; }
        public int profile_id { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
