//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class train_profile
    {
        public int profile_id { get; set; }
        public string profile_name { get; set; }
        public string profile_description { get; set; }
        public bool profile_active_YN { get; set; }
        public bool profile_editable_YN { get; set; }
        public Nullable<System.DateTime> profile_created { get; set; }
    }
}
