//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class wellness_quotient
    {
        public int wellness_id { get; set; }
        public int patient_id { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<int> longevity_importance_value { get; set; }
        public Nullable<int> longevity_committed_value { get; set; }
        public Nullable<int> longevity_ready_value { get; set; }
        public Nullable<int> longevity_confidence_value { get; set; }
        public string symptom_1_text { get; set; }
        public Nullable<int> symptom_1_value { get; set; }
        public string symptom_2_text { get; set; }
        public Nullable<int> symptom_2_value { get; set; }
        public string symptom_3_text { get; set; }
        public Nullable<int> symptom_3_value { get; set; }
        public string symptom_4_text { get; set; }
        public Nullable<int> symptom_4_value { get; set; }
        public string symptom_5_text { get; set; }
        public Nullable<int> symptom_5_value { get; set; }
        public string symptom_6_text { get; set; }
        public Nullable<int> symptom_6_value { get; set; }
        public Nullable<int> energy_value { get; set; }
        public Nullable<int> mood_value { get; set; }
        public Nullable<int> sleep_value { get; set; }
        public Nullable<int> memory_value { get; set; }
        public Nullable<int> weight_value { get; set; }
        public Nullable<int> quality_of_life_value { get; set; }
    }
}
