//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emrdev.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeroLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> UpdatedDateUTC { get; set; }
        public string LogFor { get; set; }
    }
}
